name: Deploy Docker

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with: 
          versionSpec: '5.x'

      - name: GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            docker.io/${{ github.repository }}:latest
            docker.io/${{ github.repository }}:${{ steps.gitversion.outputs.MajorMinorPatch }}
